# Diseño de Algoritmos de multiplicación Matricial

Se inicia con el Desarrollo de algoritmos que ayuden a comprender la configuración de GPU's y Paralelismo en el Lengauje de Julia.

Se usará el algoritmo con ciclos for que ayuden a generar procesos anidados y que por consecuencia requiera mejorar en su performance

#### Inicio


In [1]:
n=2
A = rand(1:10,n,n)

2×2 Array{Int64,2}:
 10  5
  1  6

In [2]:
v= rand(1:10,n)

2-element Array{Int64,1}:
 1
 3

In [23]:
A*v

2-element Array{Int64,1}:
 29
 14

In [124]:
#Establezco un arreglo de números enteros donde guarde el resultado del producto de filas y columnas
a = zeros(Int64,n,1)

2×1 Array{Int64,2}:
 0
 0

In [125]:
#Establezco un arreglo de números enteros donde guarde el resultado del producto de filas y columnas
r = zeros(Int64,n,1)


2×1 Array{Int64,2}:
 0
 0

In [114]:
r = zeros(n,1)
for i= 1:n  #Recorre filas
    for j = 1:n #Recorre columnas
        #r[n] = n^2 + 3;
        a[i,1]= A[i,j]*v[j,1]
        println(A[i,j],"X", v[j,1],"=" ,a[i,1])
        r[i,1]=r[i,1]+a[i,1]
        
        println("i=",i,"j=", j,"es ",r[i,1])
    end
    
    #println("+",a[i,1],"=", r[i,1])
end
r

8X1=8
i=1j=1es 8.0
7X3=21
i=1j=2es 29.0
5X1=5
i=2j=1es 5.0
3X3=9
i=2j=2es 14.0


2×1 Array{Float64,2}:
 29.0
 14.0

In [36]:
for i= 1:n  #Recorre filas
    for j = 1:n #Recorre columnas
        #r[n] = n^2 + 3;

        println(v[i,1])
 
    end
end


1
1
3
3


In [ ]:
#Código limpio y Comprobación
#Orden de la matriz
n=3
#Matriz 
A = rand(1:10,n,n)
A
#Vector
v= rand(1:1000,n)

#Matrices auxiliares
r = zeros(Int64,n,1)
a = zeros(Int64,n,1)


for i= 1:n  #Recorre filas
    for j = 1:n #Recorre columnas 
        a[i,1]= A[i,j]*v[j,1]
        r[i,1]=r[i,1]+a[i,1] 
    end
     
end
#println("A=",A)
#println("v=",v)
#println("resultset=",r)
#println("operacion=",A*v)
r

In [144]:
#Código limpio y Comprobación
#Orden de la matriz
n=20000
#Matriz 
A = rand(1:1000,n,n)
A
#Vector
v= rand(1:1000,n)

#Matrices auxiliares
r = zeros(Int64,n,1)
a = zeros(Int64,n,1)


for i= 1:n  #Recorre filas
    for j = 1:n #Recorre columnas 
        a[i,1]= A[i,j]*v[j,1]
        r[i,1]=r[i,1]+a[i,1] 
    end
     
end
#println("A=",A)
#println("v=",v)
#println("resultset=",r)
#println("operacion=",A*v)
r

20000×1 Array{Int64,2}:
 5010305922
 5007895450
 4993310845
 4952543345
 5010809272
 5022438413
 4999036500
 4967960054
 5013792377
 5006005759
 4962096004
 4989791102
 4987962120
          ⋮
 4977725935
 4982719357
 4968592953
 4964696316
 5031006586
 4976686953
 4998736017
 4990995477
 4994516961
 5048992459
 5032535268
 4964570621

In [147]:

A = rand(0.1:10,n,n)

20000×20000 Array{Float64,2}:
 9.1  7.1  1.1  8.1  8.1  0.1  3.1  5.1  …  2.1  0.1  2.1  4.1  2.1  7.1  4.1
 8.1  9.1  2.1  1.1  6.1  9.1  5.1  9.1     8.1  3.1  5.1  3.1  1.1  2.1  3.1
 1.1  4.1  8.1  8.1  9.1  9.1  0.1  7.1     2.1  6.1  2.1  7.1  6.1  6.1  0.1
 0.1  4.1  1.1  0.1  5.1  7.1  2.1  2.1     5.1  3.1  8.1  4.1  9.1  2.1  3.1
 2.1  9.1  5.1  2.1  7.1  8.1  2.1  4.1     5.1  1.1  5.1  1.1  5.1  3.1  9.1
 6.1  4.1  2.1  1.1  3.1  0.1  7.1  2.1  …  1.1  4.1  6.1  9.1  4.1  6.1  4.1
 0.1  4.1  3.1  9.1  0.1  3.1  7.1  7.1     0.1  4.1  8.1  5.1  0.1  3.1  6.1
 9.1  4.1  1.1  9.1  0.1  2.1  9.1  4.1     0.1  6.1  6.1  8.1  3.1  8.1  4.1
 7.1  1.1  7.1  8.1  5.1  3.1  5.1  0.1     6.1  9.1  5.1  4.1  2.1  1.1  0.1
 3.1  4.1  7.1  1.1  3.1  5.1  8.1  3.1     4.1  0.1  2.1  0.1  7.1  9.1  3.1
 3.1  5.1  0.1  4.1  1.1  0.1  2.1  6.1  …  5.1  8.1  1.1  7.1  5.1  6.1  1.1
 7.1  0.1  9.1  1.1  3.1  4.1  9.1  0.1     4.1  1.1  8.1  2.1  0.1  7.1  4.1
 6.1  3.1  9.1  7.1  8.1  0.1  0.1

# Multiplicación de Matriz Cuadrada

In [32]:
t = zeros(Int64,n,n)
for i= 1:n  #Recorre el primer indice  externo de la posición matricial
    for j = 1:n #Recorre el tercer índice externo de la posición matricial
        
        for k = 1:n  #Recorre el indice interno de la posición matricial
                println(A[i,k]  ,'X',A[k,j] ,'=', A[i,k]*A[k,j])
                t[i,j]= t[i,j]+A[i,k]*A[k,j]
         
        end
       
    end
     
end 
t

10X10=100
5X1=5
10X5=50
5X6=30
1X10=10
6X1=6
1X5=5
6X6=36


2×2 Array{Int64,2}:
 105  80
  16  41

In [23]:
A=[3 2 1;1 1 3;0 2 1]

3×3 Array{Int64,2}:
 3  2  1
 1  1  3
 0  2  1

In [24]:
A*A

3×3 Array{Int64,2}:
 11  10  10
  4   9   7
  2   4   7

In [35]:
n=3
t = zeros(Int64,n,n)

A =[3 2 1;1 1 3;0 2 1]
for i= 1:n  #Recorre el primer indice  externo de la posición matricial
    for j = 1:n #Recorre el tercer índice externo de la posición matricial
        
        for k = 1:n  #Recorre el indice interno de la posición matricial 
                t[i,j]= t[i,j]+A[i,k]*A[k,j]
         
        end
       
    end
     
end 
t

3×3 Array{Int64,2}:
 11  10  10
  4   9   7
  2   4   7

In [62]:
A =[3 2 1;1 1 3;0 2 1]

3×3 Array{Int64,2}:
 3  2  1
 1  1  3
 0  2  1

In [63]:
A^2

3×3 Array{Int64,2}:
 11  10  10
  4   9   7
  2   4   7

In [69]:
n=3
R = zeros(Int64,n,n)
A =[3 2 1;1 1 3;0 2 1]
for i= 1:n  #Recorre el primer indice  externo de la posición matricial
    for j = 1:n #Recorre el tercer índice externo de la posición matricial        
        for k = 1:n  #Recorre el indice interno de la posición matricial 
                R[i,j]= R[i,j]+A[i,k]*A[k,j]
         
        end
       
    end
     
end 
R

3×3 Array{Int64,2}:
 11  10  10
  4   9   7
  2   4   7

Transpuesta

In [38]:
n=3
q = zeros(Int64,n,n)

A =[1 0 4;0 5 0; 6 0 -9]
for i= 1:n  #Recorre el primer indice  externo de la posición matricial
    for j = 1:n #Recorre el tercer índice externo de la posición matricial
        
        #for k = 1:n  #Recorre el indice interno de la posición matricial 
                q[i,j]=  A[j,i]
         
        #end
       
    end
     
end 
A

3×3 Array{Int64,2}:
 1  0   4
 0  5   0
 6  0  -9

In [39]:
q

3×3 Array{Int64,2}:
 1  0   6
 0  5   0
 4  0  -9

In [40]:
n=3
t = zeros(Int64,n,n)
q = zeros(Int64,n,n)
A =[3 2 1;1 1 3;0 2 1]
for i= 1:n  #Recorre el primer indice  externo de la posición matricial
    for j = 1:n #Recorre el tercer índice externo de la posición matricial
        q[i,j]=  A[j,i]
        for k = 1:n  #Recorre el indice interno de la posición matricial 
                t[i,j]= t[i,j]+A[i,k]*q[k,j]
         
        end
       
    end
     
end 
t

3×3 Array{Int64,2}:
 9  3  0
 5  2  2
 5  5  5

# A*A^T

In [49]:
A =[1 0 4;0 5 0; 6 0 -9]

3×3 Array{Int64,2}:
 1  0   4
 0  5   0
 6  0  -9

In [50]:
A'

3×3 LinearAlgebra.Adjoint{Int64,Array{Int64,2}}:
 1  0   6
 0  5   0
 4  0  -9

In [51]:
A*A'

3×3 Array{Int64,2}:
  17   0  -30
   0  25    0
 -30   0  117

In [58]:
n=3
T = zeros(Int64,n,n)

A =[1 0 4;0 5 0; 6 0 -9]
for i= 1:n  #Recorre el primer indice  externo de la posición matricial
    for j = 1:n #Recorre el tercer índice externo de la posición matricial 
                T[i,j]=  A[j,i] 
    end
  
end 
R = zeros(Int64,n,n)
for i= 1:n  #Recorre el primer indice  externo de la posición matricial
    for j = 1:n #Recorre el tercer índice externo de la posición matricial 
        for k = 1:n  #Recorre el indice interno de la posición matricial
                #println(A[i,k]  ,'X',A[k,j] ,'=', A[i,k]*A[k,j])
                R[i,j]= R[i,j]+A[i,k]*T[k,j]
         
        end
       
    end
     
end 
R

3×3 Array{Int64,2}:
  17   0  -30
   0  25    0
 -30   0  117

# (A*A^T)^2

In [59]:
(A*A')^2

3×3 Array{Int64,2}:
  1189    0  -4020
     0  625      0
 -4020    0  14589

In [70]:
n=3
T = zeros(Int64,n,n)

A =[1 0 4;0 5 0; 6 0 -9]
for i= 1:n  #Recorre el primer indice  externo de la posición matricial
    for j = 1:n #Recorre el tercer índice externo de la posición matricial 
                T[i,j]=  A[j,i] 
    end
  
end 
R1 = zeros(Int64,n,n)
for i= 1:n  #Recorre el primer indice  externo de la posición matricial
    for j = 1:n #Recorre el tercer índice externo de la posición matricial 
        for k = 1:n  #Recorre el indice interno de la posición matricial
                #println(A[i,k]  ,'X',A[k,j] ,'=', A[i,k]*A[k,j])
                R1[i,j]= R1[i,j]+A[i,k]*T[k,j]
         
        end
       
    end
     
end 
R1

R2 = zeros(Int64,n,n)
for i= 1:n  #Recorre el primer indice  externo de la posición matricial
    for j = 1:n #Recorre el tercer índice externo de la posición matricial 
        for k = 1:n  #Recorre el indice interno de la posición matricial
                #println(A[i,k]  ,'X',A[k,j] ,'=', A[i,k]*A[k,j])
                R2[i,j]= R2[i,j]+R1[i,k]R1[k,j]
         
        end
       
    end
     
end 
R2

 

3×3 Array{Int64,2}:
  1189    0  -4020
     0  625      0
 -4020    0  14589