
# Multiplicación de Matrices en Ciclos For


<h2>Contenido</h2>

- [Matriz: Multiplicación](#Matriz:-Multiplicación)
- [Matriz por Vector](#Matriz-por-Vector)
- [Multiplicación de Matrices](#Multiplicación-de-Matrices)
- [Multiplicación de una matriz por su transpuesta](#Multiplicación-de-una-matriz-por-su-transpuesta)
- [El cuadrado de una matriz por su transpuesta](#El-cuadrado-de-una-matriz-por-su-transpuesta)
- [Referencías](#Referencias)

<h2>Matriz: Multiplicación</h2>


¿Cuándo se puede multiplicar dos matrices?

Cuando el número de columna de la primera matriz **es igual** al número de filas de la segunda matriz.

<img src="material-jyFms9hh.png" alt="(Multiplicación de Matrices)">

[blue_text](https://www.geogebra.org/resource/jyFms9hh/gWfr05GxoKt6c3JS/material-jyFms9hh.png)

<h2>Matriz por Vector</h2>


In [5]:
#Orden de la matriz
n=10


10

In [6]:

#Matriz 
A = rand(1:10,n,n) 



10×10 Array{Int64,2}:
  7  10  10   7  7   8   2  4  1  5
  1   7   6   2  7   7   7  2  8  3
  7   3   5   8  3   8   7  4  3  8
  6   2  10   2  6   5  10  2  5  7
  1   7   4   8  1   6   1  2  1  9
  6  10   6   2  7   9   6  2  7  8
 10   7   1   5  9  10  10  4  8  1
  4   8   4   3  1  10   4  4  7  7
 10   7   2   9  1   8   1  7  9  6
  5   5   3  10  9   1   5  9  6  1

In [7]:
#Vector
v= rand(1:10,n)

10-element Array{Int64,1}:
  3
 10
  4
  4
  6
  8
  5
  2
  5
  2

In [8]:
#Código de una función que multiplica por ciclos for entre una matriz y un vector

function matriz_vector(n::Int64, A::Array{Int64}, v::Array{Int64})
    #Matrices auxiliares
    R = zeros(Int64,n,1) 

    for i= 1:n  #Recorre filas
        for j = 1:n #Recorre columnas  
            R[i,1]=R[i,1]+A[i,j]*v[j,1]
        end
    end 
    return R 
end

matriz_vector (generic function with 1 method)

In [9]:
matriz_vector(n,A,v)

10×1 Array{Int64,2}:
 328
 288
 259
 255
 207
 349
 358
 283
 290
 254

In [17]:
#Comprobación
A*v

10-element Array{Int64,1}:
 328
 288
 259
 255
 207
 349
 358
 283
 290
 254

[Contenido](#Contenido)

<h2>Multiplicación de Matrices</h2>


In [10]:
#Código de una función que multiplica por ciclos for entre una matriz y un vector

function matriz_cuadrada(n::Int64, A::Array{Int64})
    R = zeros(Int64,n,n)    
    for i= 1:n  #Recorre el primer indice  externo de la posición matricial
        for j = 1:n #Recorre el tercer índice externo de la posición matricial        
            for k = 1:n  #Recorre el indice interno de la posición matricial 
                    R[i,j]= R[i,j]+A[i,k]*A[k,j]

            end

        end

    end 
    return R
end


matriz_cuadrada (generic function with 2 methods)

In [11]:
matriz_cuadrada(n,A)

10×10 Array{Int64,2}:
 297  391  361  316  322  428  341  208  298  362
 290  336  212  286  242  377  263  193  301  279
 342  365  306  305  334  389  330  229  304  292
 355  356  245  359  299  400  300  240  284  285
 200  229  230  199  252  236  260  164  237  201
 345  438  304  367  347  443  320  257  357  327
 384  488  338  338  342  511  324  227  359  362
 304  365  257  275  295  374  281  220  331  267
 352  416  359  309  315  426  299  247  348  333
 287  341  293  279  224  401  278  189  283  328

In [16]:
#Comprobación
A*A

10×10 Array{Int64,2}:
 297  391  361  316  322  428  341  208  298  362
 290  336  212  286  242  377  263  193  301  279
 342  365  306  305  334  389  330  229  304  292
 355  356  245  359  299  400  300  240  284  285
 200  229  230  199  252  236  260  164  237  201
 345  438  304  367  347  443  320  257  357  327
 384  488  338  338  342  511  324  227  359  362
 304  365  257  275  295  374  281  220  331  267
 352  416  359  309  315  426  299  247  348  333
 287  341  293  279  224  401  278  189  283  328

[Contenido](#Contenido)

<h2>Multiplicación de una matriz por su transpuesta</h2>


In [12]:
#Código de una función que multiplica por ciclos for entre una matriz por su matriz transpuesta

function matriz_por_transpuesta(n::Int64, A::Array{Int64})
    T = zeros(Int64,n,n)
    for i= 1:n  #Recorre el primer indice  externo de la posición matricial
        for j = 1:n #Recorre el tercer índice externo de la posición matricial 
                    T[i,j]=  A[j,i] 
        end
    end 
    
    R = zeros(Int64,n,n)
    for i= 1:n  #Recorre el primer indice  externo de la posición matricial
        for j = 1:n #Recorre el tercer índice externo de la posición matricial 
            for k = 1:n  #Recorre el indice interno de la posición matricial
                    #println(A[i,k]  ,'X',A[k,j] ,'=', A[i,k]*A[k,j])
                    R[i,j]= R[i,j]+A[i,k]*T[k,j]
            end

        end

    end 
    return R
end 

matriz_por_transpuesta (generic function with 1 method)

In [13]:
matriz_por_transpuesta(n,A)

10×10 Array{Int64,2}:
 457  301  343  326  284  404  377  322  363  313
 301  314  256  296  185  354  353  280  263  252
 343  256  358  321  253  346  361  300  350  277
 326  296  321  383  194  362  353  274  269  254
 284  185  253  194  254  266  207  243  266  185
 404  354  346  362  266  459  431  368  370  288
 377  353  361  353  207  431  537  343  401  364
 322  280  300  274  243  368  343  336  349  226
 363  263  350  269  266  370  401  349  466  326
 313  252  277  254  185  288  364  226  326  384

In [14]:
#Comprobación
A*A'

10×10 Array{Int64,2}:
 457  301  343  326  284  404  377  322  363  313
 301  314  256  296  185  354  353  280  263  252
 343  256  358  321  253  346  361  300  350  277
 326  296  321  383  194  362  353  274  269  254
 284  185  253  194  254  266  207  243  266  185
 404  354  346  362  266  459  431  368  370  288
 377  353  361  353  207  431  537  343  401  364
 322  280  300  274  243  368  343  336  349  226
 363  263  350  269  266  370  401  349  466  326
 313  252  277  254  185  288  364  226  326  384

[Contenido](#Contenido)

<h2>El cuadrado de una matriz por su transpuesta</h2>


### (A*A^T)^2

In [18]:
#Código de una función que multiplica por ciclos for entre una matriz por su matriz transpuesta

function cuadrado_matriz_por_transpuesta(n::Int64, A::Array{Int64})
    T = zeros(Int64,n,n)
    for i= 1:n  #Recorre el primer indice  externo de la posición matricial
        for j = 1:n #Recorre el tercer índice externo de la posición matricial 
                    T[i,j]=  A[j,i] 
        end

    end 
    R1 = zeros(Int64,n,n)
    for i= 1:n  #Recorre el primer indice  externo de la posición matricial
        for j = 1:n #Recorre el tercer índice externo de la posición matricial 
            for k = 1:n  #Recorre el indice interno de la posición matricial
                    #println(A[i,k]  ,'X',A[k,j] ,'=', A[i,k]*A[k,j])
                    R1[i,j]= R1[i,j]+A[i,k]*T[k,j]

            end

        end

    end 
    R1

    R2 = zeros(Int64,n,n)
    for i= 1:n  #Recorre el primer indice  externo de la posición matricial
        for j = 1:n #Recorre el tercer índice externo de la posición matricial 
            for k = 1:n  #Recorre el indice interno de la posición matricial
                    #println(A[i,k]  ,'X',A[k,j] ,'=', A[i,k]*A[k,j])
                    R2[i,j]= R2[i,j]+R1[i,k]R1[k,j]

            end

        end

    end 
    return R2
end


cuadrado_matriz_por_transpuesta (generic function with 1 method)

In [19]:
cuadrado_matriz_por_transpuesta(n,A)

10×10 Array{Int64,2}:
 1242798  1009517  1119331  1072841  …  1322745  1076270  1212573  1014130
 1009517   837572   912867   886736     1094884   881871   985242   829892
 1119331   912867  1017665   973930     1201662   975662  1101667   918696
 1072841   886736   973930   948864     1158518   933880  1042444   878621
  825844   664609   745890   706624      867926   719207   810547   666489
 1294289  1065253  1170645  1129619  …  1393726  1131445  1266389  1056116
 1322745  1094884  1201662  1158518     1449593  1155817  1306103  1102527
 1076270   881871   975662   933880     1155817   945055  1061147   876327
 1212573   985242  1101667  1042444     1306103  1061147  1209489  1002879
 1014130   829892   918696   878621     1102527   876327  1002879   857191

In [20]:
(A*A')^2

10×10 Array{Int64,2}:
 1242798  1009517  1119331  1072841  …  1322745  1076270  1212573  1014130
 1009517   837572   912867   886736     1094884   881871   985242   829892
 1119331   912867  1017665   973930     1201662   975662  1101667   918696
 1072841   886736   973930   948864     1158518   933880  1042444   878621
  825844   664609   745890   706624      867926   719207   810547   666489
 1294289  1065253  1170645  1129619  …  1393726  1131445  1266389  1056116
 1322745  1094884  1201662  1158518     1449593  1155817  1306103  1102527
 1076270   881871   975662   933880     1155817   945055  1061147   876327
 1212573   985242  1101667  1042444     1306103  1061147  1209489  1002879
 1014130   829892   918696   878621     1102527   876327  1002879   857191

[Contenido](#Contenido)

<h2>Referencias</h2>


- Allan Avendaño, Matriz Multiplicacion. Recuperado de https://www.geogebra.org/m/S6R8A2xD

- JLF, Matriz traspuesta o transpuesta. Recuperado de https://www.geogebra.org/m/mafmgjpd

[Contenido](#Contenido)
    