In [32]:
!pip install pytest-benchmark

  Created wheel for py-cpuinfo: filename=py_cpuinfo-5.0.0-py3-none-any.whl size=18689 sha256=1a12dfa68ebcee2a4d65b26b7f708ead8763061a8004684274788d29ec0fb82f
  Stored in directory: c:\users\jess\appdata\local\pip\cache\wheels\e7\3b\8e\2b1f0f6cc651cd381bb5806e5005820c6986867c46f3536101
Successfully built py-cpuinfo


In [36]:
import numpy as np

In [82]:
from time import time 

In [46]:
np.random.seed(0)

In [47]:
np

<module 'numpy' from 'c:\\phyton 372\\lib\\site-packages\\numpy\\__init__.py'>

In [49]:
size = 4096
A, B = np.random.random((size, size)), np.random.random((size, size))

In [50]:
N = 20
t = time()
for i in range(N):
    np.dot(A, B)
delta = time() - t
print('Dotted two %dx%d matrices in %0.2f s.' % (size, size, delta / N))
del A, B

Dotted two 4096x4096 matrices in 4.80 s.


## Con números Enteros

# n=10

In [ ]:
A = np.random.randint(1,50,size=(10,10))
print(a)

In [90]:
v = np.random.randint(1,50,size=( 1,10))
print(v)

[[ 1 47 47 27 35 22  6 19 40 40]]


In [91]:
A*v

array([[  12,  564, 1927, 1080, 1470,  286,   96,  418, 1200,  560],
       [  28, 1833,  329, 1026, 1645,  440,   90,  931,  400, 1560],
       [   2,  940, 2162,  621,  490, 1056,   36,  874,  480,  160],
       [  21, 1128,  658,  324,  455,  660,  276,   95, 1320, 1040],
       [  25,  517, 1410,  999, 1015,  594,   66,  323,  880, 1400],
       [   4, 1504,  376, 1269, 1330,  902,  204,  836,  480, 1160],
       [  25, 1645,  141,  756, 1260,  220,  186,  323, 1760,  320],
       [  27, 2068,  893,  405, 1400,  792,  186,  665,  400,  120],
       [  43, 1222,  329,  459,  175,  418,    6,  665,  240,  640],
       [  37, 1692,  423,  378,  455,  572,  102,  285, 1480,  400]])

In [92]:
A*A

array([[ 144,  144, 1681, 1600, 1764,  169,  256,  484,  900,  196],
       [ 784, 1521,   49, 1444, 2209,  400,  225, 2401,  100, 1521],
       [   4,  400, 2116,  529,  196, 2304,   36, 2116,  144,   16],
       [ 441,  576,  196,  144,  169,  900, 2116,   25, 1089,  676],
       [ 625,  121,  900, 1369,  841,  729,  121,  289,  484, 1225],
       [  16, 1024,   64, 2209, 1444, 1681, 1156, 1936,  144,  841],
       [ 625, 1225,    9,  784, 1296,  100,  961,  289, 1936,   64],
       [ 729, 1936,  361,  225, 1600, 1296,  961, 1225,  100,    9],
       [1849,  676,   49,  289,   25,  361,    1, 1225,   36,  256],
       [1369, 1296,   81,  196,  169,  676,  289,  225, 1369,  100]])

In [94]:
def multiplicacionAv(A, v):
   return A*v


In [95]:
show multiplicacionAv

SyntaxError: invalid syntax (<ipython-input-95-7281c104214d>, line 1)

In [34]:
@benchmark

A*A

SyntaxError: invalid syntax (<ipython-input-34-1d208e5b7273>, line 3)

# n=50

In [81]:
N = 50 
A = np.random.randint(1,50,size=(N,N))
v = np.random.randint(1,50,size=(N))

A*v



array([[1012,  357,  480, ...,  810,  504, 1638],
       [ 391,  425,  720, ..., 1755,   24,  840],
       [ 759,  289,   80, ...,  405,  576,  126],
       ...,
       [1081,  697, 1600, ..., 1080,  144,  672],
       [ 368,  561, 1600, ...,  990,  120, 1596],
       [ 621,  578, 1920, ...,  810,  312, 1218]])

In [122]:

def f1():
    i=1
    t=50
    #for i in range(t):  
    A = np.random.randint(1,50,size=(t,t))
    v = np.random.randint(1,50,size=(t))

    return  A*v

In [124]:

def f2():
    i=1
    t=100
    #for i in range(t):  
    A = np.random.randint(1,50,size=(t,t))
    v = np.random.randint(1,50,size=(t))

    return  A*v

In [123]:
f1()

array([[ 864,  432, 1521, ...,  135,   50,  264],
       [ 162,  752, 1521, ...,  600,   98,   44],
       [  36,  496, 1170, ...,  495,   98,  858],
       ...,
       [ 216,  400, 1404, ...,  390,   88,  902],
       [ 612,  240,  897, ...,  720,   38,  264],
       [ 684,  272,  390, ...,  390,   52,  880]])

In [127]:
import time
import statistics
# Assertion
import random

In [128]:
functions = f1,f2 
times = {f.__name__: [] for f in functions}

for i in range(3000):
    for _ in range(len(functions)):
        func = random.choice(functions)
        t0 = time.time()
        func()
        t1 = time.time()
        times[func.__name__].append((t1 - t0) * 1000)

for name, numbers in times.items():
    print('FUNCTION:', name, 'Used', len(numbers), 'times')
    print('\tMEDIAN', statistics.median(numbers))
    print('\tMEAN  ', statistics.mean(numbers))
    print('\tSTDEV ', statistics.stdev(numbers))

FUNCTION: f1 Used 2988 times
	MEDIAN 0.0
	MEAN   0.03907599123606242
	STDEV  0.1936142106965694
FUNCTION: f2 Used 3012 times
	MEDIAN 0.0
	MEAN   0.10725867700766757
	STDEV  0.30900789623433994


# n=100

In [104]:
print(f1)

<function f1 at 0x09E32ED0>


In [83]:

N = 100 
A = np.random.randint(1,50,size=(N,N))
v = np.random.randint(1,50,size=(N))

A*v

array([[ 924,  360,  240, ...,   82, 1472, 1188],
       [1452,  615,  120, ..., 1230, 1058,  462],
       [  33,   90,   30, ..., 1230,  414,  264],
       ...,
       [1485,   45,   80, ...,  656,  322,  693],
       [ 462,  630,  390, ...,  574, 1472, 1023],
       [1386,  210,  210, ...,  410, 2070, 1551]])

## n=1000

In [84]:

N = 1000 
A = np.random.randint(1,50,size=(N,N))
v = np.random.randint(1,50,size=(N))

A*v

array([[ 864,  279,  216, ..., 1617, 1482,  682],
       [ 504,  225,  144, ...,  441,  912,  484],
       [ 108,  117,   96, ..., 1127,  836,  154],
       ...,
       [1188,  261,  528, ..., 2303, 1368,  264],
       [ 216,  135,   12, ..., 1127, 1862,  924],
       [ 936,   81,  108, ..., 2352, 1710,  858]])

## n=2000

In [85]:

N = 2000
A = np.random.randint(1,50,size=(N,N))
v = np.random.randint(1,50,size=(N))

A*v

array([[  99, 1075, 1248, ...,  992,  703,  748],
       [ 627,  725,  130, ..., 1302,  893, 1224],
       [1353,  650,  416, ..., 1085,  475,  510],
       ...,
       [ 924,  725,   52, ..., 1271,  399, 1122],
       [ 627,  150,  130, ...,  372,  760,  476],
       [1386,  750,  728, ...,  527,  646,  510]])

## n=5000

In [86]:

N = 5000
A = np.random.randint(1,50,size=(N,N))
v = np.random.randint(1,50,size=(N))

A*v

array([[ 420,   39, 1353, ..., 1813,  644,  114],
       [ 180,   32,  891, ..., 1323,  336, 1786],
       [ 525,   25,  330, ..., 1225,  112,  874],
       ...,
       [ 420,   11, 1353, ..., 2352,  644,  266],
       [ 540,    7,  825, ..., 1127,  266, 1140],
       [ 375,   25,  429, ..., 1323,   28, 1558]])

## Con números flotantes

In [2]:
import numpy as np
random_matrix_array = np.random.rand(10, 10)
print(random_matrix_array)

[[0.45449054 0.16997893 0.7089804  ... 0.71114093 0.43814141 0.61264227]
 [0.38865389 0.36302348 0.53887777 ... 0.86289651 0.69822651 0.92123119]
 [0.98411828 0.45906326 0.66129457 ... 0.68120344 0.26636417 0.67573951]
 ...
 [0.20433261 0.80703014 0.36454149 ... 0.29902688 0.336739   0.51376608]
 [0.16571089 0.15714728 0.04972149 ... 0.81434086 0.07921392 0.24770101]
 [0.12651025 0.75908078 0.63385437 ... 0.63215767 0.48659102 0.53160641]]


In [130]:
AT

NameError: name 'AT' is not defined